on:
  push:
    # paths:
    #   - root/client/**
    branches:
      - master

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Run SSHPASS
        run: |
          sshpass \
            -p ${{ secrets.PRODUCTION_PASSWORD }} \
            ssh \
              -o 'StrictHostKeyChecking no' \
              -p ${{ secrets.SSH_PORT }} ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }} \
              'cd /var/www/apps/root/client && git checkout master && git pull --force && npm i --force && npm run build && pm2 reload all'